# -*- coding: utf-8 -*-
"""PythonDataTypeAssignment1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13UI7Xr311oU1bLO9S5iZ12f0vAAFTcS9
"""

'''1. Write a program to add two lists index-wise. Create a new list that contains the 0th index item from both the list,
then the 1st index item, and so on till the last element. any leftover items will get added at the end of the new list.'''

	# Given List:

	# list1 = ["M", "na", "i", "Ra"]
	# list2 = ["y", "me", "s", "hul"]

	# Output:

	# [['M','y'], ['na', me'], ['i', 's'], ['Ra', 'hul']]


list1 = ["M", "na", "i", "Ra"]
list2 = ["y", "me", "s", "hul"]

result = []

for i in range(len(list1)):
    result.append([list1[i], list2[i]])

print(result)

'''2. Write a program to add item 7000 after 6000 in the following Python List'''

	# list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]
	# Output:

	# [10, 20, [300, 400, [5000, 6000, 7000], 500], 30, 40]

list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]

list1[2][2].append(7000)

print(list1)

'''3. Suppose you are given a list of candy and another list of same size representing no of items of respective candy.'''

	# i.e -
	# candy_list = ['Jelly Belly','Kit Kat','Double Bubble','Milky Way','Three Musketeers']
	# no_of_items = [10,20,34,74,32]
	# Write a program to show no. of items of each candy type.

	# Output:

	# Jelly Belly-10
	# Kit Kat-20
	# Double Bubble-34
	# Milky Way-74
	# Three Musketeers-32

candy_list = ['Jelly Belly','Kit Kat','Double Bubble','Milky Way','Three Musketeers']
no_of_items = [10,20,34,74,32]

for candy, items in zip(candy_list, no_of_items):
    print(candy + "-" + str(items))

'''4. Running Sum on list Write a program to print a list after performing running sum on it.'''

	# i.e:
	# Input:

	# list1 = [1,2,3,4,5,6]
	# Output:

	# [1,3,6,10,15,21]

list1 = [1,2,3,4,5,6]

running_sum = []
total = 0

for i in list1:
    total = total + i
    running_sum.append(total)

print(running_sum)

'''5. You are given a list of integers. You are asked to make a list by running
through elements of the list by adding all elements greater and itself.'''

	# i.e. Say given list is [2,4,6,10,1] resultant list will be [22,20,10,23].
	# For 1st element 2 ->> these are greater (4+6+10) values and 2 itself so on adding becomes 22.
	# For 2nd element 4 ->> greater elements are (6, 10) and 4 itself, so on adding 20
	# like wise for all other elememts.

	# [2,4,6,10,1]-->[22,20,16,10,23]

list1 = [2,4,6,10,1]

result = [sum(j for j in list1 if j >= i) for i in list1]

print(result)

'''6. Find list of common unique items from two list. and show in increasing order'''

	# Input
	# num1 = [23,45,67,78,89,34]
	# num2 = [34,89,55,56,39,67]
	# Output:
	# [34, 67, 89]

num1 = [23,45,67,78,89,34]
num2 = [34,89,55,56,39,67]

common = sorted(set(num1) & set(num2))

print(common)

'''7. Sort a list of alphanumeric strings based on product value of numeric character in it.
     If in any string there is no numeric character take it's product value as 1.'''

	# Input:
	# ['1ac21', '23fg', '456', '098d','1','kls']

	# Output:
	# ['456', '23fg', '1ac21', '1', 'kls', '098d']

lst = ['1ac21', '23fg', '456', '098d','1','kls']

def product_value(s):
    product = 1
    found = False

    for ch in s:
        if ch.isdigit():
            product *= int(ch)
            found = True

    if not found:
        return 1
    return product

result = sorted(lst, key=product_value, reverse=True)

print(result)

'''8. Write a program that can find the max number of each row of a matrix
	Example:'''

	# Input:
	# [[1,2,3],[4,5,6],[7,8,9]]

	# Output:
	# [3,6,9]

matrix = [[1,2,3],[4,5,6],[7,8,9]]

result = []

for row in matrix:
    result.append(max(row))

print(result)

'''9. Shortlist Students for a Job role Ask user to input students record and store in tuples for each record.
 Then Ask user to input three things he wants in the candidate- Primary Skill, Higher Education, Year of Graduation.'''

	# Show every students record in form of tuples if matches all required criteria.

	# It is assumed that there will be only one primry skill.

	# If no such candidate found, print No such candidate

	# Input:

	# Enter No of records- 2
	# Enter Details of student-1
	# Enter Student name- Manohar
	# Enter Higher Education- B.Tech
	# Enter Primary Skill- Python
	# Enter Year of Graduation- 2022
	# Enter Details of student-2
	# Enter Student name- Ponian
	# Enter Higher Education- B.Sc.
	# Enter Primary Skill- C++
	# Enter Year of Graduation- 2020

	# Enter Job Role Requirement
	# Enter Skill- Python
	# Enter Higher Education- B.Tech
	# Enter Year of Graduation- 2022
	# Output

	# ('Manohar', 'B.tech', 'Python', '2022')

records = []

n = int(input("Enter No of records: "))

for i in range(n):
    print("Enter Details of student-", i+1)

    name = input("Enter Student name: ")
    edu = input("Enter Higher Education: ")
    skill = input("Enter Primary Skill: ")
    year = input("Enter Year of Graduation: ")

    records.append((name, edu, skill, year))

print("\nEnter Job Role Requirement")
req_skill = input("Enter Skill: ")
req_edu = input("Enter Higher Education: ")
req_year = input("Enter Year of Graduation: ")

found = False

for rec in records:
    if rec[1] == req_edu and rec[2] == req_skill and rec[3] == req_year:
        print(rec)
        found = True

if found == False:
    print("No such candidate")

'''10. Write a program to find set of common elements in three lists using sets.'''

	# Input : ar1 = [1, 5, 10, 20, 40, 80]
	# 		ar2 = [6, 7, 20, 80, 100]
	# 		ar3 = [3, 4, 15, 20, 30, 70, 80, 120]
	# Output : [80, 20]


ar1 = [1, 5, 10, 20, 40, 80]
ar2 = [6, 7, 20, 80, 100]
ar3 = [3, 4, 15, 20, 30, 70, 80, 120]

result = list(set(ar1) & set(ar2) & set(ar3))

print(result)

'''11. Write a program to count unique number of vowels using sets in a given string. Lowercase and upercase vowels will be taken as different.'''

	# Input:
	# Str1 = "hands-on data science mentorship progrAm with live classes at affordable fee only on CampusX"

	# Output:
	# No of unique vowels-6
str1 = "hands-on data science mentorship progrAm with live classes at affordable fee only on CampusX"

vowels = "aeiouAEIOU"
unique_vowels = set()

for ch in str1:
    if ch in vowels:
        unique_vowels.add(ch)

print("No of unique vowels-", len(unique_vowels))

'''12. Intersection of two lists. Intersection of two list means we need to take all those elements
which are common to both of the initial lists and store them into another list. Only use using list-comprehension.'''

	# Example 1:
	# Input:

	# lst1 = {15, 9, 10, 56, 23, 78, 5, 4, 9}
	# lst2 = {9, 4, 5, 36, 47, 26, 10, 45, 87}
	# Output:

	# [9, 10, 4, 5]
	# Example 2:

	# Input:

	# lst1 = {4, 9, 1, 17, 11, 26, 28, 54, 69}
	# lst2 = {9, 9, 74, 21, 45, 11, 63, 28, 26}
	# Output:

	# [9, 11, 26, 28]

lst1 = [15, 9, 10, 56, 23, 78, 5, 4, 9]
lst2 = [9, 4, 5, 36, 47, 26, 10, 45, 87]

result = [i for i in lst1 if i in lst2]

print(result)

'''13. Convert a list of Tuples into Dictionary.'''

	# Example 1:


	# Input:
	# [("akash", 10), ("gaurav", 12), ("anand", 14), ("suraj", 20), ("akhil", 25), ("ashish", 30)]

  # Output:
	# {'akash': [10], 'gaurav': [12], 'anand': [14], 'suraj': [20], 'akhil': [25], 'ashish': [30]}

  # Example 2:

	# Input:
	# [('A', 1), ('B', 2), ('C', 3)]

	# Output:
	# {'A': [1], 'B': [2], 'C': [3]}

data = [("akash", 10), ("gaurav", 12), ("anand", 14), ("suraj", 20), ("akhil", 25), ("ashish", 30)]

result = {}

for key, value in data:
    result[key] = [value]

print(result)

'''# 14. Write a Python function that takes a list and returns a new list with unique elements of the first list.'''
# 	Exercise 1:
# 	Input:
# 	[1,2,3,3,3,3,4,5]

# 	Output:
# 	[1, 2, 3, 4, 5]

data = [1,2,3,3,3,3,4,5]
result = list(set(data))
print(result)



'''15.  Write a Python program to print the even numbers from a given list.'''

		# Sample List : [1, 2, 3, 4, 5, 6, 7, 8, 9]
		# Expected Result : [2, 4, 6, 8]

data = [1, 2, 3, 4, 5, 6, 7, 8, 9]
even_numbers = [i for i in data if i % 2 == 0]
print(even_numbers)

# 16. Write a Python function to check whether a number is perfect or not.¶
# 	A Perfect number is a number that is half the sum of all of its positive divisors (including itself).

# 	Example :
# 	The first perfect number is 6, because 1, 2, and 3 are its proper positive divisors, and 1 + 2 + 3 = 6.
# 	Equivalently, the number 6 is equal to half the sum of all its positive divisors: ( 1 + 2 + 3 + 6 ) / 2 = 6.

# 	The next perfect number is 28 = 1 + 2 + 4 + 7 + 14. This is followed by the perfect numbers 496 and 8128.

def is_perfect(n):
    if n <= 0:
        return False
    divisor_sum = 0
    for i in range(1, n):
        if n % i == 0:
            divisor_sum += i
    return divisor_sum == n

def check_perfect(num):
    sum = 0

    for i in range(1, num):
        if num % i == 0:
            sum = sum + i

    if sum == num:
        print(num, "is a Perfect Number")
    else:
        print(num, "is not a Perfect Number")


n = int(input("Enter a number: "))
check_perfect(n)

'''17. Write a Python function to concatenate any no of dictionaries to create a new one.'''
	# Sample Dictionary :
	# dic1={1:10, 2:20}
	# dic2={3:30, 4:40}
	# dic3={5:50,6:60}
	# Expected Result : {1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}

def concat_dict(*dicts):
    result = {}

    for d in dicts:
        result.update(d)

    return result


dic1 = {1:10, 2:20}
dic2 = {3:30, 4:40}
dic3 = {5:50, 6:60}

print(concat_dict(dic1, dic2, dic3))

'''18. Write a python function that receives a list of integers and prints out a histogram of bin size 10'''

	# Input:
	# [13,42,15,37,22,39,41,50]
	# Output:
	# {11-20:2,21-30:1,31-40:2,41-50:3}

def print_histogram(nums):
    if not nums:
        print("{}")
        return

    min_val = min(nums)
    max_val = max(nums)

    bins_start = ((min_val - 1) // 10) * 10 + 1
    bins_end = ((max_val + 9) // 10) * 10

    hist = {}

    for start in range(bins_start, bins_end + 1, 10):
        end = start + 9
        count = sum(1 for x in nums if start <= x <= end)

        if count > 0:
            hist[f"{start}-{end}"] = count

    print(hist)


nums = [13,42,15,37,22,39,41,50]
print_histogram(nums)







