# -*- coding: utf-8 -*-
"""data_type_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ict7ceVKPcEYxg3v1tkJAvl30AAv79UQ

1. Write a program to add two lists index-wise. Create a new list that contains the 0th index item from both the list, then the 1st index item, and so on till the last element. any leftover items will get added at the end of the new list.

	Given List:

	list1 = ["M", "na", "i", "Ra"]
	list2 = ["y", "me", "s", "hul"]
[[i,j] for (i,j) in zip(l1,l2)]

	Output:

	[['M','y'], ['na', me'], ['i', 's'], ['Ra', 'hul']]
"""

# Given lists
list1 = ["M", "na", "i", "Ra"]
list2 = ["y", "me", "s", "hul"]

# Combine index-wise
result = [[i, j] for i, j in zip(list1, list2)]

# Output
print(result)

"""2. Write a program to add item 7000 after 6000 in the following Python List

	list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]

Output:

	[10, 20, [300, 400, [5000, 6000, 7000], 500], 30, 40]

"""

# Given list
list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]

# Access the inner list and append 7000
list1[2][2].append(7000)

# Output
print(list1)

"""3. Suppose you are given a list of candy and another list of same size representing no of items of respective candy.

	i.e -

	candy_list = ['Jelly Belly','Kit Kat','Double Bubble','Milky Way','Three Musketeers']
	no_of_items = [10,20,34,74,32]
	Write a program to show no. of items of each candy type.

	Output:

	Jelly Belly-10
	Kit Kat-20(
	Double Bubble-34
	Milky Way-74
	Three Musketeers-32

"""

# Given lists
candy_list = ['Jelly Belly','Kit Kat','Double Bubble','Milky Way','Three Musketeers']
no_of_items = [10, 20, 34, 74, 32]

# Combine and print
for candy, count in zip(candy_list, no_of_items):
    print(f"{candy}-{count}")

"""4. Running Sum on list Write a program to print a list after performing running sum on it.

	i.e:

	Input:

	list1 = [1,2,3,4,5,6]
	Output:

	[1,3,6,10,15,21]

"""

# Given list
list1 = [1, 2, 3, 4, 5, 6]

# Running sum
running_sum = []
total = 0

for num in list1:
    total += num
    running_sum.append(total)

# Output
print(running_sum)

"""5. You are given a list of integers. You are asked to make a list by running through elements of the list by adding all elements greater and itself.

	i.e. Say given list is [2,4,6,10,1] resultant list will be [22,20,10,23].

	For 1st element 2 ->> these are greater (4+6+10) values and 2 itself so on adding becomes 22.

	For 2nd element 4 ->> greater elements are (6, 10) and 4 itself, so on adding 20

	like wise for all other elememts.

	[2,4,6,10,1]-->[22,20,16,10,23]

"""

# Given list
list1 = [2, 4, 6, 10, 1]

# Result list
result = []

for x in list1:
    total = x
    for y in list1:
        if y > x:
            total += y
    result.append(total)

# Output
print(result)

"""6. Find list of common unique items from two list. and show in increasing order

	Input

	num1 = [23,45,67,78,89,34]
	num2 = [34,89,55,56,39,67]
	Output:

	[34, 67, 89]

"""

# Given list
list1 = [1, 2, 3, 4, 5, 6]

# Running sum
running_sum = []
total = 0

for num in list1:
    total += num
    running_sum.append(total)

# Output
print(running_sum)

"""7. Sort a list of alphanumeric strings based on product value of numeric character in it. If in any string there is no numeric character take it's product value as 1.

	Input:

	['1ac21', '23fg', '456', '098d','1','kls']
	Output:

	['456', '23fg', '1ac21', '1', 'kls', '098d']

"""

from functools import reduce

# Given list
data = ['1ac21', '23fg', '456', '098d', '1', 'kls']

# Function to calculate product of digits
def product_of_digits(s):
    digits = [int(ch) for ch in s if ch.isdigit()]
    if not digits:
        return 1
    return reduce(lambda x, y: x * y, digits)

# Sort based on product of digits
result = sorted(data, key=lambda x: product_of_digits(x), reverse=True)

# Output
print(result)

"""8. Write a program that can find the max number of each row of a matrix
	Example:

	Input:

	[[1,2,3],[4,5,6],[7,8,9]]
	Output:

	[3,6,9]

"""

# Given matrix
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Find max of each row
result = [max(row) for row in matrix]

# Output
print(result)

"""9. Shortlist Students for a Job role Ask user to input students record and store in tuples for each record. Then Ask user to input three things he wants in the candidate- Primary Skill, Higher Education, Year of Graduation.

	Show every students record in form of tuples if matches all required criteria.

	It is assumed that there will be only one primry skill.

	If no such candidate found, print No such candidate

	Input:

	Enter No of records- 2
	Enter Details of student-1
	Enter Student name- Manohar
	Enter Higher Education- B.Tech
	Enter Primary Skill- Python
	Enter Year of Graduation- 2022
	Enter Details of student-2
	Enter Student name- Ponian
	Enter Higher Education- B.Sc.
	Enter Primary Skill- C++
	Enter Year of Graduation- 2020

	Enter Job Role Requirement
	Enter Skill- Python
	Enter Higher Education- B.Tech
	Enter Year of Graduation- 2022
	Output

	('Manohar', 'B.tech', 'Python', '2022')


"""

records = []

n = int(input("Enter No of records: "))

for i in range(n):
    print("Enter Details of student-", i+1)

    name = input("Enter Student name: ")
    edu = input("Enter Higher Education: ")
    skill = input("Enter Primary Skill: ")
    year = input("Enter Year of Graduation: ")

    records.append((name, edu, skill, year))

print("\nEnter Job Role Requirement")
req_skill = input("Enter Skill: ")
req_edu = input("Enter Higher Education: ")
req_year = input("Enter Year of Graduation: ")

found = False

for rec in records:
    if rec[1] == req_edu and rec[2] == req_skill and rec[3] == req_year:
        print(rec)
        found = True

if found == False:
    print("No such candidate")

"""10. Write a program to find set of common elements in three lists using sets.

	Input : ar1 = [1, 5, 10, 20, 40, 80]
			ar2 = [6, 7, 20, 80, 100]
			ar3 = [3, 4, 15, 20, 30, 70, 80, 120]

	Output : [80, 20]

"""

# Given lists
ar1 = [1, 5, 10, 20, 40, 80]
ar2 = [6, 7, 20, 80, 100]
ar3 = [3, 4, 15, 20, 30, 70, 80, 120]

# Find common elements
result = list(set(ar1) & set(ar2) & set(ar3))

# Output
print(result)

"""11. Write a program to count unique number of vowels using sets in a given string. Lowercase and upercase vowels will be taken as different.

	Input:

	Str1 = "hands-on data science mentorship progrAm with live classes at affordable fee only on CampusX"
	Output:

	No of unique vowels-6

"""

# Given string
Str1 = "hands-on data science mentorship progrAm with live classes at affordable fee only on CampusX"

# Define vowels (case-sensitive)
vowels = set("aeiouAEIOU")

# Find unique vowels in the string
unique_vowels = set([ch for ch in Str1 if ch in vowels])

# Output
print("No of unique vowels-", len(unique_vowels))

"""12. Intersection of two lists. Intersection of two list means we need to take all those elements which are common to both of the initial lists and store them into another list. Only use using list-comprehension.
	Example 1:

	Input:

	lst1 = {15, 9, 10, 56, 23, 78, 5, 4, 9}
	lst2 = {9, 4, 5, 36, 47, 26, 10, 45, 87}
	Output:

	[9, 10, 4, 5]
	Example 2:

	Input:

	lst1 = {4, 9, 1, 17, 11, 26, 28, 54, 69}
	lst2 = {9, 9, 74, 21, 45, 11, 63, 28, 26}
	Output:

	[9, 11, 26, 28]

"""

lst1 = [4, 9, 1, 17, 11, 26, 28, 54, 69]
lst2 = [9, 9, 74, 21, 45, 11, 63, 28, 26]

result = [x for x in lst1 if x in lst2]
result = list(dict.fromkeys(result))  # remove duplicates

print(result)

"""13. Convert a list of Tuples into Dictionary.
	Example 1:

	Input:

	[("akash", 10), ("gaurav", 12), ("anand", 14), ("suraj", 20), ("akhil", 25), ("ashish", 30)]
	Output:

	{'akash': [10], 'gaurav': [12], 'anand': [14], 'suraj': [20], 'akhil': [25], 'ashish': [30]}
	Example 2:

	Input:

	[('A', 1), ('B', 2), ('C', 3)]
	Output:

	{'A': [1], 'B': [2], 'C': [3]}

"""

data = [("akash", 10), ("gaurav", 12), ("anand", 14),
        ("suraj", 20), ("akhil", 25), ("ashish", 30)]

result = {}

for key, value in data:
    result.setdefault(key, []).append(value)

print(result)

"""14. Write a Python function that takes a list and returns a new list with unique elements of the first list.
	Exercise 1:

	Input:

	[1,2,3,3,3,3,4,5]
	Output:

	[1, 2, 3, 4, 5]

"""

def unique_list(lst):
    result = []
    for item in lst:
        if item not in result:
            result.append(item)
    return result

# Example
print(unique_list([1, 2, 3, 3, 3, 3, 4, 5]))

"""15.  Write a Python program to print the even numbers from a given list.
		Sample List : [1, 2, 3, 4, 5, 6, 7, 8, 9]
		Expected Result : [2, 4, 6, 8]

"""

# Given list
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Find even numbers
even_numbers = [x for x in numbers if x % 2 == 0]

# Output
print(even_numbers)

"""16. Write a Python function to check whether a number is perfect or not.¶
	A Perfect number is a number that is half the sum of all of its positive divisors (including itself).

	Example :

	The first perfect number is 6, because 1, 2, and 3 are its proper positive divisors, and 1 + 2 + 3 = 6.
	Equivalently, the number 6 is equal to half the sum of all its positive divisors: ( 1 + 2 + 3 + 6 ) / 2 = 6.

	The next perfect number is 28 = 1 + 2 + 4 + 7 + 14. This is followed by the perfect numbers 496 and 8128.

"""

def is_perfect(n):
    if n <= 0:
        return False

    total = 0

    # Find sum of proper divisors
    for i in range(1, n):
        if n % i == 0:
            total += i

    return total == n

# Example usage
print(is_perfect(6))    # True
print(is_perfect(28))   # True
print(is_perfect(10))   # False

"""17. Write a Python function to concatenate any no of dictionaries to create a new one.
	Sample Dictionary :
	dic1={1:10, 2:20}
	dic2={3:30, 4:40}
	dic3={5:50,6:60}
	Expected Result : {1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}

"""

def concat_dicts(*dicts):
    result = {}
    for d in dicts:
        result.update(d)
    return result


# Sample dictionaries
dic1 = {1: 10, 2: 20}
dic2 = {3: 30, 4: 40}
dic3 = {5: 50, 6: 60}

# Function call
final_dict = concat_dicts(dic1, dic2, dic3)

print(final_dict)

"""18. Write a python function that receives a list of integers and prints out a histogram of bin size 10

	Input:
	[13,42,15,37,22,39,41,50]
	Output:
	{11-20:2,21-30:1,31-40:2,41-50:3}

"""

def histogram_bin10(numbers):
    bins = {}

    for num in numbers:
        # Find bin range
        lower = (num // 10) * 10 + 1
        upper = lower + 9

        # Fix for multiples of 10 (like 10, 20, 30...)
        if num % 10 == 0:
            lower -= 10
            upper -= 10

        key = f"{lower}-{upper}"

        # Count frequency
        bins[key] = bins.get(key, 0) + 1

    # Sort bins properly
    sorted_bins = dict(sorted(bins.items(), key=lambda x: int(x[0].split('-')[0])))

    print(sorted_bins)


# Input
data = [13, 42, 15, 37, 22, 39, 41, 50]

# Function call
histogram_bin10(data)