# -*- coding: utf-8 -*-
"""Exception_handling_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NYdPrnjAR0yhcv4m-4veehJqvAfmij-o

1. Write a Python program to handle a ZeroDivisionError exception when dividing a number by zero.
"""

def handle_zero_division():
    print("\n1. ZeroDivisionError Handler")
    try:
        numerator = float(input("Enter numerator: "))
        denominator = float(input("Enter denominator: "))
        result = numerator / denominator
        print(f"Result: {result}")
    except ZeroDivisionError:
        print("Error: Cannot divide by zero! Please enter a non-zero denominator.")
    except ValueError:
        print("Error: Please enter valid numbers.")
    except Exception as e:
        print(f"Unexpected error: {e}")

"""2. Write a Python program that prompts the user to input an integer and raises a ValueError exception if the input is not a valid integer.

"""

try:
    user_input = input("Enter an integer: ")

    # Check if input is a valid integer
    if not user_input.lstrip("-").isdigit():
        raise ValueError("Input is not a valid integer!")

    number = int(user_input)
    print("You entered:", number)

except ValueError as e:
    print(" Error:", e)

"""3. Write a Python program that opens a file and handles a FileNotFoundError exception if the file does not exist.

"""

try:
    file_name = input("Enter file name to open: ")

    file = open(file_name, "r")
    content = file.read()

    print("\n File Content:\n")
    print(content)

    file.close()

except FileNotFoundError:
    print(" Error: File not found. Please check the file name and try again.")

"""4. Write a Python program that prompts the user to input two numbers and raises a TypeError exception if the inputs are not numerical.

"""

try:
    num1 = input("Enter first number: ")
    num2 = input("Enter second number: ")

    # Check if both inputs are numeric (integer or float)
    if not (num1.replace(".", "", 1).lstrip("-").isdigit() and
            num2.replace(".", "", 1).lstrip("-").isdigit()):
        raise TypeError("Inputs must be numeric!")

    num1 = float(num1)
    num2 = float(num2)

    print("Sum:", num1 + num2)

except TypeError as e:
    print(" Error:", e)

"""5. Write a Python program that opens a file and handles a PermissionError exception if there is a permission issue.

"""

try:
    file_name = input("Enter file name: ")

    # Try to open file in read mode
    with open(file_name, "r") as file:
        content = file.read()
        print("\n File Content:\n")
        print(content)

except FileNotFoundError:
    print(" Error: File not found.")

except PermissionError:
    print(" Error: You do not have permission to access this file.")

"""6. Write a Python program that executes an operation on a list and handles an IndexError exception if the index is out of range.

"""

try:
    numbers = [10, 20, 30, 40, 50]

    index = int(input("Enter index (0 to 4): "))

    print("Value at index:", numbers[index])

except IndexError:
    print(" Error: Index is out of range!")

except ValueError:
    print(" Error: Please enter a valid integer index!")

"""7. Write a Python program that executes division and handles an ArithmeticError exception if there is an arithmetic error.

"""

try:
    num1 = float(input("Enter numerator: "))
    num2 = float(input("Enter denominator: "))

    result = num1 / num2
    print("Result:", result)

except ArithmeticError:
    print(" Error: An arithmetic error occurred during calculation!")