# -*- coding: utf-8 -*-
"""File_IO_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K8SVsKY6OuOEW03br5tffBf3sjgLJrQQ

1. Write a Python program to read an entire text file.
"""

# Read an entire text file

file_name = input("Enter the file name (with path if needed): ")

try:
    with open(file_name, "r") as file:
        content = file.read()
        print("\nFile Content:\n")
        print(content)

except FileNotFoundError:
    print("Error: File not found. Please check the file name/path.")

except PermissionError:
    print("Error: You don't have permission to read this file.")

except Exception as e:
    print("An unexpected error occurred:", e)

"""2. Write a Python program to read first n lines of a file.

"""

# Read first n lines of a file

file_name = input("Enter file name: ")
n = int(input("Enter number of lines to read: "))

try:
    with open(file_name, "r") as file:
        print(f"\nFirst {n} lines of the file:\n")

        for i in range(n):
            line = file.readline()
            if line == "":  # stops if file has fewer lines
                break
            print(line, end="")

except FileNotFoundError:
    print("Error: File not found.")
except PermissionError:
    print("Error: Permission denied.")
except Exception as e:
    print("Unexpected error:", e)

"""3. Write a Python program to append text to a file and display the text.

"""

# Append text to a file and display content

file_name = input("Enter file name: ")
text = input("Enter text to append: ")

try:
    # Append mode
    with open(file_name, "a") as file:
        file.write(text + "\n")

    # Read and display updated file content
    with open(file_name, "r") as file:
        content = file.read()
        print("\nUpdated File Content:\n")
        print(content)

except FileNotFoundError:
    print("Error: File not found.")
except PermissionError:
    print("Error: Permission denied.")
except Exception as e:
    print("Unexpected error:", e)

"""4. Write a Python program to read last n lines of a file.

"""

# Read last n lines of a file

file_name = input("Enter file name: ")
n = int(input("Enter number of last lines to read: "))

try:
    with open(file_name, "r") as file:
        lines = file.readlines()   # read all lines into a list

        last_lines = lines[-n:]    # get last n lines

        print(f"\nLast {n} lines of the file:\n")
        for line in last_lines:
            print(line, end="")

except FileNotFoundError:
    print("Error: File not found.")
except PermissionError:
    print("Error: Permission denied.")
except Exception as e:
    print("Unexpected error:", e)

"""5. Write a Python program to read a file line by line and store it into a list.

"""

# Read file line by line and store into a list

file_name = input("Enter file name: ")

try:
    with open(file_name, "r") as file:
        lines_list = []

        for line in file:
            lines_list.append(line.strip())  # remove newline and store

    print("\nFile content stored in list:")
    print(lines_list)

except FileNotFoundError:
    print("Error: File not found.")
except PermissionError:
    print("Error: Permission denied.")
except Exception as e:
    print("Unexpected error:", e)

"""6. Write a Python program to read a file line by line store it into a variable.

"""

# Read file line by line and store into a variable

file_name = input("Enter file name: ")

try:
    with open(file_name, "r") as file:
        content = ""   # variable to store file data

        for line in file:
            content += line  # add each line to variable

    print("\nFile content stored in variable:\n")
    print(content)

except FileNotFoundError:
    print("Error: File not found.")
except PermissionError:
    print("Error: Permission denied.")
except Exception as e:
    print("Unexpected error:", e)

"""7. Write a python program to find the longest words.

"""

# Find the longest word(s) in a file

file_name = input("Enter file name: ")

try:
    with open(file_name, "r") as file:
        text = file.read()

        # Split text into words
        words = text.split()

        # Find maximum length
        max_length = max(len(word) for word in words)

        # Collect all longest words
        longest_words = [word for word in words if len(word) == max_length]

    print("\nLongest word(s) in the file:")
    print(set(longest_words))  # set removes duplicates

except FileNotFoundError:
    print("Error: File not found.")
except PermissionError:
    print("Error: Permission denied.")
except Exception as e:
    print("Unexpected error:", e)

"""8. Write a Python program to count the number of lines in a text file.

"""

# Count number of lines in a text file

file_name = input("Enter file name: ")

try:
    with open(file_name, "r") as file:
        line_count = 0

        for line in file:
            line_count += 1

    print("\nTotal number of lines in the file:", line_count)

except FileNotFoundError:
    print("Error: File not found.")
except PermissionError:
    print("Error: Permission denied.")
except Exception as e:
    print("Unexpected error:", e)

"""9. Write a Python program to count the frequency of words in a file.

"""

# Count frequency of words in a file

file_name = input("Enter file name: ")

try:
    with open(file_name, "r") as file:
        text = file.read().lower()   # convert to lowercase for uniformity

        words = text.split()         # split into words

        frequency = {}

        for word in words:
            if word in frequency:
                frequency[word] += 1
            else:
                frequency[word] = 1

    print("\nWord Frequency:")
    for word, count in frequency.items():
        print(word, ":", count)

except FileNotFoundError:
    print("Error: File not found.")
except PermissionError:
    print("Error: Permission denied.")
except Exception as e:
    print("Unexpected error:", e)

"""10. Write a Python program to get the file size of a plain file.

"""

import os

# Get file size

file_name = input("Enter file name: ")

try:
    size = os.path.getsize(file_name)
    print("\nFile size:", size, "bytes")

except FileNotFoundError:
    print("Error: File not found.")
except PermissionError:
    print("Error: Permission denied.")
except Exception as e:
    print("Unexpected error:", e)

"""11. Write a Python program to write a list to a file.

"""

# Write a list to a file

file_name = input("Enter file name: ")

# Sample list (you can also take input from user)
data_list = ["Apple", "Banana", "Mango", "Orange"]

try:
    with open(file_name, "w") as file:
        for item in data_list:
            file.write(item + "\n")  # write each item in new line

    print("List has been written to the file successfully.")

except PermissionError:
    print("Error: Permission denied.")
except Exception as e:
    print("Unexpected error:", e)

"""12. Write a Python program to copy the contents of a file to another file .

"""

# Copy contents of one file to another file

source_file = input("Enter source file name: ")
destination_file = input("Enter destination file name: ")

try:
    with open(source_file, "r") as src:
        content = src.read()

    with open(destination_file, "w") as dest:
        dest.write(content)

    print("File copied successfully!")

except FileNotFoundError:
    print("Error: Source file not found.")
except PermissionError:
    print("Error: Permission denied.")
except Exception as e:
    print("Unexpected error:", e)

"""13. Write a Python program to read a random line from a file.

"""

import random

# Read a random line from a file

file_name = input("Enter file name: ")

try:
    with open(file_name, "r") as file:
        lines = file.readlines()

        if lines:  # check file is not empty
            random_line = random.choice(lines)
            print("\nRandom line from file:")
            print(random_line.strip())
        else:
            print("The file is empty.")

except FileNotFoundError:
    print("Error: File not found.")
except PermissionError:
    print("Error: Permission denied.")
except Exception as e:
    print("Unexpected error:", e)

"""14. Write a Python program to assess if a file is closed or not.

"""

# Check if a file is closed or not

file_name = input("Enter file name: ")

try:
    file = open(file_name, "r")

    # Check status before closing
    print("Is file closed?", file.closed)

    file.close()

    # Check status after closing
    print("Is file closed now?", file.closed)

except FileNotFoundError:
    print("Error: File not found.")
except PermissionError:
    print("Error: Permission denied.")
except Exception as e:
    print("Unexpected error:", e)

"""15.Write a Python program that takes a text file as input and returns the number of words of a given text file.

"""

# Count number of words in a text file

file_name = input("Enter file name: ")

try:
    with open(file_name, "r") as file:
        text = file.read()   # read full file content

        words = text.split() # split text into words
        word_count = len(words)

    print("\nTotal number of words in the file:", word_count)

except FileNotFoundError:
    print("Error: File not found.")
except PermissionError:
    print("Error: Permission denied.")
except Exception as e:
    print("Unexpected error:", e)