# -*- coding: utf-8 -*-
"""python_challenges_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wsxJQCl2oi_7kOvvQbdRog-LvsGCVZ-d

Challenge: Student Marks Analyzer

Create a Python program that allows a user to input student names along with their marks and then calculates useful statistics.
Your program should:
1. Let the user input multiple students with their marks (name + integer score).
2. After input is complete, display:
   - Average marks
   - Highest marks and student(s) who scored it
   - Lowest marks and student(s) who scored it
   - Total number of students

Bonus:
- Allow the user to enter all data first, then view the report
- Format output clearly in a report-style layout
- Prevent duplicate student names
"""

# Student Marks Analyzer

students = {}

print("Enter student data (type 'done' to finish)\n")

# Input loop
while True:
    name = input("Enter student name: ")

    if name.lower() == "done":
        break

    if name in students:
        print(" Duplicate name not allowed! Try again.\n")
        continue

    try:
        marks = int(input("Enter marks: "))

        if marks < 0:
            print("Marks cannot be negative!\n")
            continue

        students[name] = marks

    except ValueError:
        print(" Please enter a valid integer for marks!\n")

# If no data entered
if not students:
    print("\nNo student data entered.")
else:
    total_students = len(students)
    total_marks = sum(students.values())
    average = total_marks / total_students

    highest_mark = max(students.values())
    lowest_mark = min(students.values())

    highest_students = [name for name, mark in students.items() if mark == highest_mark]
    lowest_students = [name for name, mark in students.items() if mark == lowest_mark]

    # Report Output
    print("\n" + "=" * 40)
    print("        STUDENT MARKS REPORT")
    print("=" * 40)

    print(f"Total Students : {total_students}")
    print(f"Average Marks  : {average:.2f}")

    print(f"\nHighest Marks  : {highest_mark}")
    print("Top Student(s) :", ", ".join(highest_students))

    print(f"\nLowest Marks   : {lowest_mark}")
    print("Lowest Student(s):", ", ".join(lowest_students))

    print("=" * 40)

""" Challenge: CLI Contact Book (CSV-Powered)

Create a terminal-based contact book tool that stores and manages contacts using a CSV file.

Your program should:
1. Ask the user to choose one of the following options:
   - Add a new contact
   - View all contacts
   - Search for a contact by name
   - Exit
2. Store contacts in a file called `contacts.csv` with columns:
   - Name
   - Phone
   - Email
3. If the file doesn't exist, create it automatically.
4. Keep the interface clean and clear.

Example:
Add Contact
View All Contacts
Search Contact
Exit

Bonus:
- Format the contact list in a table-like view
- Allow partial match search
- Prevent duplicate names from being added


"""

import csv
import os

FILE_NAME = "contacts.csv"

# Create file if not exists
if not os.path.exists(FILE_NAME):
    with open(FILE_NAME, "w", newline="") as file:
        writer = csv.writer(file)
        writer.writerow(["Name", "Phone", "Email"])


def add_contact():
    name = input("Enter Name: ").strip()

    # Check duplicate
    contacts = read_contacts()
    for contact in contacts:
        if contact[0].lower() == name.lower():
            print("⚠ Contact already exists!\n")
            return

    phone = input("Enter Phone: ").strip()
    email = input("Enter Email: ").strip()

    with open(FILE_NAME, "a", newline="") as file:
        writer = csv.writer(file)
        writer.writerow([name, phone, email])

    print(" Contact added successfully!\n")


def read_contacts():
    with open(FILE_NAME, "r") as file:
        reader = csv.reader(file)
        next(reader)  # skip header
        return list(reader)


def view_contacts():
    contacts = read_contacts()

    if not contacts:
        print("No contacts found.\n")
        return

    print("\n{:<20} {:<15} {:<25}".format("Name", "Phone", "Email"))
    print("-" * 60)

    for name, phone, email in contacts:
        print("{:<20} {:<15} {:<25}".format(name, phone, email))

    print()


def search_contact():
    query = input("Enter name to search: ").strip().lower()
    contacts = read_contacts()

    results = [
        c for c in contacts if query in c[0].lower()
    ]  # partial match

    if not results:
        print(" No matching contact found.\n")
        return

    print("\nSearch Results:")
    print("{:<20} {:<15} {:<25}".format("Name", "Phone", "Email"))
    print("-" * 60)

    for name, phone, email in results:
        print("{:<20} {:<15} {:<25}".format(name, phone, email))

    print()


def menu():
    while True:
        print("\n====== CONTACT BOOK ======")
        print("1. Add Contact")
        print("2. View All Contacts")
        print("3. Search Contact")
        print("4. Exit")

        choice = input("Enter choice (1-4): ")

        if choice == "1":
            add_contact()
        elif choice == "2":
            view_contacts()
        elif choice == "3":
            search_contact()
        elif choice == "4":
            print("Exiting... Goodbye!")
            break
        else:
            print(" Invalid choice. Try again!\n")


# Run program
menu()

""" Challenge:  Personal Movie Tracker with JSON

Create a Python CLI tool that lets users maintain their own personal movie database, like a mini IMDb.

Your program should:
1. Store all movie data in a `movies.json` file.
2. Each movie should have:
   - Title
   - Genre
   - Rating (out of 10)
3. Allow the user to:
   - Add a movie
   - View all movies
   - Search movies by title or genre
   - Exit the app

Bonus:
- Prevent duplicate titles from being added
- Format output in a clean table
- Use JSON for reading/writing structured data


"""

import json
import os

FILE_NAME = "movies.json"

# Create file if not exists
if not os.path.exists(FILE_NAME):
    with open(FILE_NAME, "w") as file:
        json.dump([], file)


# Load movies
def load_movies():
    with open(FILE_NAME, "r") as file:
        return json.load(file)


# Save movies
def save_movies(movies):
    with open(FILE_NAME, "w") as file:
        json.dump(movies, file, indent=4)


# Add movie
def add_movie():
    movies = load_movies()

    title = input("Enter Movie Title: ").strip()

    # Prevent duplicate titles
    for movie in movies:
        if movie["title"].lower() == title.lower():
            print("⚠ Movie already exists!\n")
            return

    genre = input("Enter Genre: ").strip()

    try:
        rating = float(input("Enter Rating (out of 10): "))

        if rating < 0 or rating > 10:
            print(" Rating must be between 0 and 10!\n")
            return

    except ValueError:
        print(" Invalid rating!\n")
        return

    movies.append({
        "title": title,
        "genre": genre,
        "rating": rating
    })

    save_movies(movies)
    print(" Movie added successfully!\n")


# View movies
def view_movies():
    movies = load_movies()

    if not movies:
        print("No movies found.\n")
        return

    print("\n{:<25} {:<15} {:<10}".format("Title", "Genre", "Rating"))
    print("-" * 55)

    for movie in movies:
        print("{:<25} {:<15} {:<10}".format(
            movie["title"],
            movie["genre"],
            movie["rating"]
        ))

    print()


# Search movie
def search_movie():
    movies = load_movies()
    query = input("Search by title or genre: ").strip().lower()

    results = [
        m for m in movies
        if query in m["title"].lower() or query in m["genre"].lower()
    ]

    if not results:
        print(" No matching movies found.\n")
        return

    print("\nSearch Results:")
    print("{:<25} {:<15} {:<10}".format("Title", "Genre", "Rating"))
    print("-" * 55)

    for movie in results:
        print("{:<25} {:<15} {:<10}".format(
            movie["title"],
            movie["genre"],
            movie["rating"]
        ))

    print()


# Menu
def menu():
    while True:
        print("\n====== MOVIE TRACKER ======")
        print("1. Add Movie")
        print("2. View All Movies")
        print("3. Search Movie")
        print("4. Exit")

        choice = input("Enter choice (1-4): ")

        if choice == "1":
            add_movie()
        elif choice == "2":
            view_movies()
        elif choice == "3":
            search_movie()
        elif choice == "4":
            print("Exiting... Goodbye 4")
            break
        else:
            print("⚠ Invalid choice!\n")


# Run program
menu()

""" Challenge: Real-Time Weather Logger (API + CSV)

Build a Python CLI tool that fetches real-time weather data for a given city and logs it to a CSV file for daily tracking.

Your program should:
1. Ask the user for a city name.
2. Fetch weather data using the OpenWeatherMap API.
3. Store the following in a CSV file (`weather_log.csv`):
   - Date (auto-filled as today's date)
   - City
   - Temperature (in °C)
   - Weather condition (e.g., Clear, Rain)
4. Prevent duplicate entries for the same city on the same day.
5. Allow users to:
   - Add new weather log
   - View all logs
   - Show average, highest, lowest temperatures, and most frequent condition

Bonus:
- Format the output like a table
- Handle API failures and invalid city names gracefully


"""

import requests
import csv
import os
from datetime import datetime
from collections import Counter

API_KEY = "YOUR_API_KEY"
CSV_FILE = "weather_log.csv"


# ---------------- FETCH WEATHER ---------------- #
def get_weather(city):
    try:
        url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"
        response = requests.get(url)
        data = response.json()

        if response.status_code != 200:
            print(" Error:", data.get("message", "Unable to fetch data"))
            return None

        temp = data["main"]["temp"]
        condition = data["weather"][0]["main"]

        return temp, condition

    except requests.exceptions.RequestException:
        print(" Network error!")
        return None


# ---------------- INIT CSV ---------------- #
def init_csv():
    if not os.path.exists(CSV_FILE):
        with open(CSV_FILE, "w", newline="") as file:
            writer = csv.writer(file)
            writer.writerow(["Date", "City", "Temperature", "Condition"])


# ---------------- CHECK DUPLICATE ---------------- #
def is_duplicate(city, date):
    if not os.path.exists(CSV_FILE):
        return False

    with open(CSV_FILE, "r") as file:
        reader = csv.reader(file)
        next(reader, None)

        for row in reader:
            if row and row[0] == date and row[1].lower() == city.lower():
                return True
    return False


# ---------------- ADD LOG ---------------- #
def add_log():
    city = input("Enter city name: ").strip()
    date = datetime.today().strftime("%Y-%m-%d")

    if is_duplicate(city, date):
        print(" Entry already exists for this city today!")
        return

    weather = get_weather(city)
    if not weather:
        return

    temp, condition = weather

    with open(CSV_FILE, "a", newline="") as file:
        writer = csv.writer(file)
        writer.writerow([date, city, temp, condition])

    print(" Weather logged successfully!")


# ---------------- VIEW LOGS ---------------- #
def view_logs():
    if not os.path.exists(CSV_FILE):
        print("No logs found.")
        return

    with open(CSV_FILE, "r") as file:
        reader = csv.reader(file)
        rows = list(reader)

        if len(rows) <= 1:
            print("No data available.")
            return

        print("\n WEATHER LOGS\n")
        for row in rows:
            print("{:<12} {:<15} {:<10} {:<15}".format(*row))


# ---------------- STATISTICS ---------------- #
def show_stats():
    if not os.path.exists(CSV_FILE):
        print("No data available.")
        return

    temps = []
    conditions = []

    with open(CSV_FILE, "r") as file:
        reader = csv.reader(file)
        next(reader, None)

        for row in reader:
            try:
                temps.append(float(row[2]))
                conditions.append(row[3])
            except:
                pass

    if not temps:
        print("No valid data.")
        return

    avg_temp = sum(temps) / len(temps)
    max_temp = max(temps)
    min_temp = min(temps)

    most_common = Counter(conditions).most_common(1)[0][0]

    print("\n WEATHER STATS")
    print(f"Average Temperature: {avg_temp:.2f}°C")
    print(f"Highest Temperature: {max_temp}°C")
    print(f"Lowest Temperature: {min_temp}°C")
    print(f"Most Frequent Condition: {most_common}")


# ---------------- MENU ---------------- #
def menu():
    init_csv()

    while True:
        print("\n====== WEATHER LOGGER ======")
        print("1. Add Weather Log")
        print("2. View Logs")
        print("3. Show Statistics")
        print("4. Exit")

        choice = input("Enter choice: ")

        if choice == "1":
            add_log()
        elif choice == "2":
            view_logs()
        elif choice == "3":
            show_stats()
        elif choice == "4":
            print("👋 Exiting...")
            break
        else:
            print("Invalid choice!")


# ---------------- RUN ---------------- #
if __name__ == "__main__":
    menu()